# staging.properties
# Delta Pharmacy - Staging Environment Configuration
app.url=https://staging.deltapharmacy.com
app.name=Delta Pharmacy - Staging
api.base.url=https://staging-api.deltapharmacy.com/pharmacy-api/api

browser=chrome
headless=true
maximize.window=true
delete.cookies=true

implicit.wait=15
explicit.wait=25
page.load.timeout=40

app.username=customer.staging@pharmacy.com
app.password=staging123
admin.username=admin.staging@pharmacy.com
admin.password=adminStaging123
pharmacist.username=pharmacist.staging@pharmacy.com
pharmacist.password=pharmaStaging123

take.screenshot.on.failure=true
enable.video.recording=true
enable.logging=true
log.level=INFO

max.retry.count=2
thread.count=2